### ISSUE TITLE
I found a new issue

### ISSUE THREAD

**Issue by BrooklyBloxOfficial** [netlify-templates/nextjs-toolbox#29]
Replit: Updating package configuration

--> npm install @components/Footer @components/Header @components/JokeBlock @styles/globals.css next @components/FeedbackForm
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@components%2fFeedbackForm - Not found
npm ERR! 404 
npm ERR! 404  '@components/FeedbackForm@*' is not in this registry.
npm ERR! 404 This package name is not valid, because 
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-05-28T07_50_42_686Z-debug.log
exit status 1

**Comment by maxcell** [comment]
Howdy @BrooklyBloxOfficial! Did Replit try to import those packages themselves? The shorthand `@components/Footer`and others are a specific configuration that let's reference our `src/components` folder and not really packages themselves.

You don't need to update them through a package manager but if you want to modify them you can navigate to the `src/components` folder.
